services:
  webapi:
    container_name: my-api
    #image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: dis
      POSTGRES_PASSWORD: dis
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # pgAdmin will be accessible on port 8080
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:

